export const questions = [
  { q: "Kdo nese zodpovědnost za to, že je ve vzorku nalezena zakázaná látka?", options: ["Trenér a týmový doktor", "Sportovec (Princip striktní odpovědnosti)", "Výrobce doplňku stravy"], correct: 1 },
  { q: "Můžeš odmítnout dopingovou kontrolu, pokud spěcháš na letadlo?", options: ["Ano, pokud to doložíš letenkou", "Ne, hrozí za to stejný trest jako za doping", "Ano, test se jen odloží"], correct: 1 },
  { q: "Jsou běžné léky na chřipku (např. Modafen) při závodech povoleny?", options: ["Ne, obsahují pseudoefedrin", "Ano, léky z lékárny jsou bezpečné", "Ano, ale max 2 tablety"], correct: 0 },
  { q: "Jaký je standardní zákaz činnosti (ban) za úmyslný doping?", options: ["1 rok", "2 roky", "4 roky"], correct: 2 },
  { q: "Může ti lékař podat infuzi s vitamíny o objemu 200 ml?", options: ["Ne, infuze nad 100 ml za 12 hod. jsou zakázány", "Ano, vitamíny nejsou doping", "Ano, v přítomnosti trenéra"], correct: 0 },
  { q: "Je kokain nebo marihuana považována za doping?", options: ["Ne, jde o rekreační drogu", "Ano, při soutěži jsou tyto látky zakázány", "Pouze v motorsportu"], correct: 1 },
  { q: "Co je to TUE (Terapeutická výjimka)?", options: ["Povolení pro astmatiky nechodit na testy", "Legální možnost užívat zakázaný lék ze zdravotních důvodů", "Korupční úplatek"], correct: 1 },
  { q: "Zaručuje nápis '100% Přírodní' na doplňku, že neobsahuje doping?", options: ["Ano, příroda neškodí", "Ne, doplňky bývají často kontaminované", "Ano, pokud je z EU"], correct: 1 },
  { q: "Je kofein na seznamu zakázaných látek WADA?", options: ["Ano, je to silný stimulant", "Ne, kofein je povolen (ale je v monitorovacím programu)", "Jen pro nezletilé"], correct: 1 },
  { q: "Může být potrestán i trenér, který sportovci doping obstaral?", options: ["Ano, hrozí mu zákaz činnosti", "Ne, pravidla platí jen pro sportovce", "Dostane pouze pokutu"], correct: 0 },
  { q: "Co znamená zkratka WADA?", options: ["Světová asociace doktorů", "Světová antidopingová agentura", "Západní antidopingová aliance"], correct: 1 },
  { q: "Co jsou tzv. 'Místa pobytu' (Whereabouts)?", options: ["Adresy sportovních stadionů", "Systém, kam sportovec hlásí, kde se nachází, aby mohl být testován", "GPS lokátor na noze"], correct: 1 },
  { q: "Lze žádat o Terapeutickou výjimku (TUE) až poté, co mám pozitivní test?", options: ["Ano, kdykoliv", "Zpravidla ne, musí se žádat předem", "Ne, zakazuje to EU"], correct: 1 },
  { q: "Jsou finální tresty za doping po uzavření případu veřejné?", options: ["Ne, GDPR to zakazuje", "Ano, jména hříšníků se zveřejňují", "Záleží na sportovci"], correct: 1 },
  { q: "Jaký je trest za úmyslné zmanipulování vzorku moči?", options: ["Žádný, test se jen opakuje", "Zákaz činnosti obvykle na 4 roky", "Pokuta 10 000 Kč"], correct: 1 },
  { q: "Co je 'Biologický pas sportovce'?", options: ["Kartička komisaře", "Dlouhodobé sledování parametrů krve a moči pro odhalení anomálií", "Zdravotní karta"], correct: 1 },
  { q: "Smí sportovec, který má trest za doping, trénovat se svým klubem?", options: ["Ano, trénink povolen je", "Ne, nesmí se účastnit žádné organizované činnosti pod svazem", "Ano, bez platu"], correct: 1 },
  { q: "Je porušením pravidel i samotné VLASTNICTVÍ dopingových látek (v tašce)?", options: ["Ne, musím to mít v krvi", "Ano, vlastnictví zakázaných látek je dopingovým proviněním", "Jen více než 10ks"], correct: 1 },
  { q: "Kdo všechno může nařídit dopingovou kontrolu?", options: ["Jen WADA", "Národní antidopingová organizace, WADA nebo mezinárodní federace", "Pouze policie"], correct: 1 },
  { q: "Může jít nezletilý sportovec na dopingovou kontrolu sám?", options: ["Musí jít vždy sám", "Má právo mít s sebou zástupce (např. trenéra/rodiče)", "Nezletilí se netestují"], correct: 1 },
  { q: "Co se stane, pokud sportovec zmešká test, protože nebyl na nahlášeném místě pobytu?", options: ["Dostává rovnou trest na 4 roky", "Zaznamená se to. Tři zmeškání za 12 měsíců znamenají trest.", "Test se přesune"], correct: 1 },
  { q: "Lze se vymluvit na to, že mi zakázanou pilulku dal doktor a já mu věřil?", options: ["Ano, vina padá na doktora", "Ne, platí princip striktní odpovědnosti – sportovec ručí za to, co polyká", "Rozhoduje trenér"], correct: 1 },
  { q: "Může být sportovec testován u sebe doma v neděli ráno?", options: ["Ne, testy probíhají jen v práci", "Ne, o víkendu se netestuje", "Ano, sportovci mohou být testováni kdykoliv a kdekoliv"], correct: 2 },
  { q: "Jsou všechny léky proti astmatu povolené?", options: ["Ano, astma je běžná nemoc", "Ne, většina z nich obsahuje zakázané látky a vyžaduje Terapeutickou výjimku", "Ano, pokud se inhalují"], correct: 1 }
];
